### ISSUE TITLE
Atualizar imagem de Niemeyer no portal

### ISSUE THREAD

**Issue by danielbarboni** [codhab/plataform#27]
![niemeyer3](https://cloud.githubusercontent.com/assets/12968021/8284512/9ab64118-18d3-11e5-9150-b88520b3cdeb.jpg)

**Comment by danielbarboni** [comment]
Deixar a imagem escondida por enquanto, apenas substituindo a anterior.

**Comment by danielbarboni** [comment]
Remover a barra branca que aparece entre o footer da página e a imagem atual de niemeyer. A foto nova em anexo deve iniciar logo acima do footer da página.

**Comment by victorvitalino** [comment]
Margem branca removida, imagem alterada.
