### ISSUE TITLE
corrigir as cores padrão no slider.

### ISSUE THREAD

**Issue by danielbarboni** [codhab/plataform#82]

**Comment by danielbarboni** [comment]
As cores padrão do slider não foram corrigidas, portanto este Issue não deveria ser fechado. Vide imagens a seguir, onde o slider de Habitação que deveria ser verde, aparece com a cor azul.

![habit_cores](https://cloud.githubusercontent.com/assets/12968021/8825279/5049ba5e-3054-11e5-8306-e4c368728521.png)


O mesmo ocorre com regularização, cujo slider aparece em azul, ao invés de amarelo.

Peço que seja corrigido ainda hoje este padrão de cores, dado que compromete o design original do site, dado o tempo em que este item está aberto e o aparente baixo grau de complexidade do mesmo.

Caso haja algum problema técnico com esta correção, favor informar.

**Comment by victorvitalino** [comment]
Essa issue foi fechada pois ela está corrigida na nova plataforma, este é o board da plataforma, a board do cms se encontra no link : https://github.com/codhab/cms#boards?repos=37148698

Não focamos na correção pois a mesma já esta corrigida na nova versão e existem outras demandas mais urgentes.
